### ISSUE TITLE
how to start this project

### ISSUE THREAD

**Issue by shuqianchi** [angieto/burger-builder#1]
when i npm start or npm install,it always throw an error

**Comment by angieto** [comment]
hi Octopus, what kind of error did you run into?

**Comment by shuqianchi** [comment]
Error: Cannot find module 'chalk' ,but when i install chalk , it show me Cannot read property 'match' of undefined

**Comment by shuqianchi** [comment]
i used cnpm install it, and instal other module

**Comment by shuqianchi** [comment]
how can i install this →→Error: Cannot find module 'babel-preset-react-app/webpack-overrides', when i sudo npm install it tell me   Error while executing....  
sudo cnpm install→→[@babel-preset-react-app/webpack-overrides] install  from git github:babel-preset-react-app/webpack-overrides, may be very slow, please keep patience
⠇ [0/1] Installing @babel-preset-react-app/webpack-overridesdownload tarball failed: GET https://github.com/babel-preset-react-app/webpack-overrides/tarball/master response 404 status, try to clone repository now.

**Comment by shuqianchi** [comment]
oh!!! i run it!!!  i used sudo cnpm install ,install all modules !!!!

**Comment by angieto** [comment]
Nice! Enjoy :D

**Comment by shuqianchi** [comment]
thank u answer my issue (*σ´∀`)σ
